# Generated by Django 3.2.9 on 2021-12-07 19:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0003_alter_anket_age"),
    ]

    operations = [
        migrations.AlterField(
            model_name="anket",
            name="age",
            field=models.IntegerField(),
        ),
    ]
