# Generated by Django 3.2.9 on 2021-12-07 19:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_alter_anket_age'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='anketa',
        ),
        migrations.AddField(
            model_name='anket',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='api.user'),
            preserve_default=False,
        ),
    ]
