# Generated by Django 3.2.9 on 2021-12-21 20:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_user_username'),
    ]

    operations = [
        migrations.CreateModel(
            name='Dislike',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('who_dislike', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='author_dislike', to='api.user')),
                ('whom_dislike', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dislike_partner', to='api.user')),
            ],
        ),
    ]
